version: '3.7'
services:
  mongodb_repro:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_repro:/data/db

volumes:
  mongodb_repro:
